### ISSUE TITLE
Status: CSS Variables are shipped by latest Firefox

### ISSUE THREAD

**Issue by am11** [MicrosoftEdge/Status#120]
The status says its under development by Firefox: http://status.modern.ie/cssvariables?term=css%20variable 

However, the feature is shipped by Firefox; this is now a valid CSS:

``` css
div {
    --a: 2px;
    top: var(--a);
}
```

Please update the status.
