### ISSUE TITLE
Add support to modifications in color

### ISSUE THREAD

**Issue by sandhilt** [MicrosoftEdge/Status#415]
like this : https://drafts.csswg.org/css-color/#modifying-colors

``` css
.style-ish {
   background-color: color(black a(70%));
}
```

or more complex like this

``` css
:root {
  --main : dodgerblue;
  --secondary: #333;
}

.style-me {
  background: linear-gradient(var(--main), color( var(--secondary) alpha(.2) blackness(.8)));
}
```
